stages:
  - setup
  - test
  - teardown

include:
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/templates/hidden-jobs.yml
  - https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/templates/teardown.yml

variables:
  JULIA_IMAGE: 468665244580.dkr.ecr.us-east-1.amazonaws.com/julia-gitlab-ci:1.0

"1.0 (Linux, 64-bit, Shell)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  extends: .test_shell_1_0

"1.1 (Linux, 64-bit, Shell)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  extends: .test_shell_1_1

"Nightly (Linux, 64-bit, Shell)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  extends: .test_shell_nightly
