stages:
  - test
  - coverage
  - docs

.test_shell: &test_shell
  artifacts:
    name: "$CI_JOB_NAME coverage"
    expire_in: 1 week
    paths:
      - "$CI_JOB_NAME coverage/"
  before_script:
    - curl -s -o julia-ci https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/julia-ci
    - chmod +x julia-ci
    - ./julia-ci install $JULIA_VERSION
  script:
    - source julia-ci export
    - ./julia-ci test
    - ./julia-ci coverage
  after_script:
    - ./julia-ci clean

.test_shell_06: &test_shell_06
  variables:
    JULIA_VERSION: "0.6"
  <<: *test_shell

.test_shell_07: &test_shell_07
  variables:
    JULIA_VERSION: "0.7"
  <<: *test_shell

.test_shell_10: &test_shell_10
  variables:
    JULIA_VERSION: "1.0"
  <<: *test_shell

.test_shell_nightly: &test_shell_nightly
  variables:
    JULIA_VERSION: "nightly"
  allow_failure: true
  <<: *test_shell

.test_docker: &test_docker
  artifacts:
    name: "$CI_JOB_NAME coverage"
    expire_in: 1 week
    paths:
      - "$CI_JOB_NAME coverage"
  script:
    - julia -e "Pkg.clone(pwd()); Pkg.build(\"$PKG_NAME\"); Pkg.test(\"$PKG_NAME\"; coverage=true)"
    - julia-coverage "$PKG_NAME"

"0.6 (Linux, 64-bit, Docker)":
  image: 292522074875.dkr.ecr.us-east-1.amazonaws.com/julia-gitlab-ci:0.6
  tags:
    - linux
    - 64-bit
    - docker-ci
  <<: *test_docker

"0.7 (Linux, 64-bit, Shell)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  <<: *test_shell_07

"1.0 (Linux, 64-bit, Shell)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  <<: *test_shell_10

"Nightly (Linux, 64-bit, Shell)":
  tags:
    - linux
    - 64-bit
    - shell-ci
  <<: *test_shell_nightly

"Coverage":
  stage: coverage
  image: 292522074875.dkr.ecr.us-east-1.amazonaws.com/julia-gitlab-ci:0.6
  coverage: /Test Coverage (\d+\.\d+%)/
  artifacts:
    name: combined_coverage
    expire_in: 1 week
    paths:
      - combined_coverage/
  tags:
    - linux
    - docker-ci
  script:
    - genhtml --version
    - mkdir $CI_PROJECT_DIR/combined_coverage
    - cp -r $CI_PROJECT_DIR/src $CI_PROJECT_DIR/combined_coverage/
    - ls */*.info | xargs -I{} echo '--summary "{}"' | xargs lcov --directory src
    - echo "Test Coverage $(genhtml -o $CI_PROJECT_DIR/combined_coverage --no-prefix */coverage.info 2>&1 | grep lines | awk '{print $2}')"
    - find $CI_PROJECT_DIR/combined_coverage -type f -name "*.jl" -delete

pages:
  stage: docs
  only:
    - tags  # special keyword for all tags
  variables:
    JULIA_VERSION: "0.6"
  before_script:
    - curl -s -o julia-ci https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/julia-ci
    - chmod +x julia-ci
    - ./julia-ci install $JULIA_VERSION
  script:
    - source julia-ci export
    - ./julia-ci publish-docs public
  after_script:
    - ./julia-ci clean
  artifacts:
    paths:
      - public/
