---
include:
  - project: invenia/gitlab-ci-helper
    file: /templates/julia.yml

variables:
  # Only include Linux 64-bit jobs in the job matrix
  os: "linux"        
  platform: "x86_64"

"Benchmark":
  variables:
    mem_unit: MiB
    time_unit: ms
    alloc_unit: "K"
  extends:
    - .benchmark_code

"Benchmark Dependencies":
  needs: ["Benchmark"]
  dependencies: ["Benchmark"]
  extends:
    - .benchmark_deps
  allow_failure: true
